from typing import TypedDict, List, Optional, Any

class ArbitrageState(TypedDict):
    """
    State for the eBay Sniper (Arbitrage) Agent.
    """
    search_query: Optional[str]
    category_id: Optional[str] # New field for Category Surfing
    niche: Optional[str]            # Active Niche (from Discovery)
    
    # Autonomous Discovery
    pending_queries: List[str]      # List of queries generated by Planner

    # Raw processed listings
    raw_listings: List[dict]        
    
    # Filtered candidates that passed LLM triage
    targets_for_valuation: List[dict] 
    
    # Final list of actionable deals
    final_deals: List[dict]

    # Rejected deals (filtered by reflection agent)
    rejected_deals: Optional[List[dict]]

    # Error tracking
    error_message: Optional[str]

    # Flags
    is_complete: bool
    is_autonomous: Optional[bool]

    # For debugging/tracing
    trace_id: Optional[str]
